Fix pre-commit errors with black
https://github.com/OCA/product-attribute/runs/4165598273?check_suite_focus=true#step:4:112

```
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repowzndsk7_/py_env-python3/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/.cache/pre-commit/repowzndsk7_/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
    from typed_ast import ast3, ast27
  File "/home/runner/.cache/pre-commit/repowzndsk7_/py_env-python3/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: /home/runner/.cache/pre-commit/repowzndsk7_/py_env-python3/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
```

Appears to be an error introduced by https://github.com/python/typed_ast with Python 3.9. As explained in https://github.com/python/typed_ast#python-38, this library won't be supporting Python 3.8+

Black fixes this after release 21, but we can't bump the version in older branches without reformatting, so we need to pin the Python version instead.

TT32912